CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar NOT NULL,
  "password" varchar NOT NULL
);

CREATE TABLE "collections" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "owner_id" int NOT NULL
);

CREATE TABLE "web_apps" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "url" varchar NOT NULL,
  "image" varchar NOT NULL,
  "collection_id" int
);

CREATE TABLE "my_lists" (
  "user_id" int,
  "app_id" int,
  PRIMARY KEY ("user_id", "app_id")
);

CREATE INDEX ON "collections" ("owner_id");

CREATE INDEX ON "web_apps" ("collection_id");

CREATE INDEX ON "my_lists" ("user_id");

ALTER TABLE "collections" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");

ALTER TABLE "web_apps" ADD FOREIGN KEY ("collection_id") REFERENCES "collections" ("id");

ALTER TABLE "my_lists" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "my_lists" ADD FOREIGN KEY ("app_id") REFERENCES "web_apps" ("id");
